### ISSUE TITLE
2FA Code is correct, but still can't login.

### ISSUE THREAD

**Issue by Cicini** [ChiHangChen/SteamDailyBoosterPack#1]
2FA Code is correct, but still can't login.
I have confirmed that the username and password are correct, but I can't find the reason, please help me, thank you.

System: Debian 12
Pyhton Version: 3.11.2

```
root@shiro ~/SteamDailyBoosterPack # python3 SteamMakeBoosterPack.py FVJ2Q
ERROR:root:Login failed, please check account info or authenticator code, error 'transfer_parameters'
Traceback (most recent call last):
  File "/root/SteamDailyBoosterPack/SteamMakeBoosterPack.py", line 45, in login
    self.account_session = self.account.login(twofactor_code=str(twofactor_code_inp))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/steam/webauth.py", line 209, in login
    self._finalize_login(resp)
  File "/usr/local/lib/python3.11/dist-packages/steam/webauth.py", line 153, in _finalize_login
    self.steam_id = SteamID(login_response['transfer_parameters']['steamid'])
                            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'transfer_parameters'
```

**Comment by Cicini** [comment]
~~The previous version of the code seems to work~~
~~https://github.com/ChiHangChen/SteamDailyBoosterPack/tree/a91cd2a93d97464007f0c8a654c6767c61be3145~~
Well, it doesn't seem to automatically make packs.
```
root@shiro ~/SteamDailyBoosterPack # python3 SteamMakeBoosterPack_Legacy.py BX4QC
WARNING:root:Load config success!
WARNING:root:Getting login information...
WARNING:root:Logging in as ******** using 2FA: BX4QC...
WARNING:root:Login response: {'success': True, 'requires_twofactor': False, 'login_complete': True}
WARNING:root:return text : null
> /root/SteamDailyBoosterPack/SteamMakeBoosterPack_Legacy.py(122)run()
-> try:
(Pdb)
```

**Comment by ChiHangChen** [comment]
This repo currently not functioning die to steam backend API changed, and this repo using https://github.com/ValvePython/steam
which hasn't updated yet. 
so once it update this repo should work again.

**Comment by Cicini** [comment]
> This repo currently not functioning die to steam backend API changed, and this repo using https://github.com/ValvePython/steam which hasn't updated yet. so once it update this repo should work again.

Thank you.
